language: scala
scala:
  - 2.11.5
jdk:
  - oraclejdk8
  - openjdk8
script:
  - mvn clean package
  - sbt ++$TRAVIS_SCALA_VERSION test
notifications:
  email:
    - konstantin.spitsyn@gmail.com
    - MMiroshnichenko@luxoft.com
